### ISSUE TITLE
Images are not getting resized properly.

### ISSUE THREAD

**Issue by sanjay-github** [josegonzalez/cakephp-upload#295]
I tried to create a thumbnail for different sizes 
'thumbnailSizes' => array(
//                    'xvga' => '1024x768',
                    'vga' => '210x110',
                    'thumb' => '60x60'
                )

I am using cakePHP 2.6.2 version and as such , it was working fine but specially on size specified in vga argument as you can see above, it was giving improper image. 

i.e slightly cut from top and bottom I guess.

I think , the resizing code needs to be rewritten to create proper thumbnails.

**Comment by davidyell** [comment]
This is a problem with your configuration. Generation of thumbnails takes a number of different arguments, you have asked the plugin to crap your images to fit the specific dimensions you have set.

If you want images to scale instead of crop you need to specify that in your configuration. Please [check out the thumbnail documentation](http://cakephp-upload.readthedocs.org/en/latest/thumbnails.html) to see the different options.

In your case, you might want to try one of the following,
```
'[1024x768]',
'1024w'
```

**Comment by sanjay-github** [comment]
Thanks davidyell  !!
