### ISSUE TITLE
Turkish Character Problem

### ISSUE THREAD

**Issue by feciOne** [josegonzalez/cakephp-upload#305]
When I tried to upload a file which is named as "çiçek.jpg", plugin doesnot recognize the "ç" and exchange the character "ç" with correponding charset code (File name changed by the plugin). So file is uploaded but it could not find the file again, because MySQL can handle this and it reserve the orginal file name as "çiçek". Any way to say your plugin to use charset like utf-8? Thanks!..

**Comment by davidyell** [comment]
You could use the file rename callback method to solve this and rename the file as you see fit. The plugin doesn't have a character set other than what you configure in your application.

**Comment by feciOne** [comment]
But my application charset was set to UTF-8. Thus, it should work properly. I will apply your solution. Thanks...

**Comment by davidyell** [comment]
Well with the filename it'll be down to the hosting machines system rather than your application. So it could be that your hosting doesn't support the character.

As I say, I'd personally use the rename callback method and use the PHP Intl extension to transliterate the characters so they'll save properly.

**Comment by feciOne** [comment]
Problem solved. Thanks...
