### ISSUE TITLE
Upgrade to Cake3.

### ISSUE THREAD

**Issue by genellern** [josegonzalez/cakephp-upload#311]
Hi, I'm working on a project that uses this plugin, I'm upgrading to Cakephp 3, so I was wondering if is in your plans to upgrade this plugin?

Thanks.

**Comment by josegonzalez** [comment]
Every once in a while I think about doing this, but then whatever project I am working on doesn't require it anymore. If you're willing to pay for it, then I can sit down and write the code, otherwise I have no immediate plans that don't require alcohol and boredom.

Sorry.

**Comment by dreamingmind** [comment]
I've got the code sitting on my machine as I contemplate tacking this task. But I haven't quite committed to it yet.

**Comment by josegonzalez** [comment]
To be quite honest, if I were to reimplement this, it would be using a combination of [Intervention Image](http://image.intervention.io/) and [Flysystem](http://flysystem.thephpleague.com/).

**Comment by dreamingmind** [comment]
hmm... those are worth looking into.

**Comment by davidyell** [comment]
Just to note that I've created a plugin for Cake 3 which works similarly to this plugin.
https://github.com/davidyell/CakePHP3-Proffer

**Comment by josegonzalez** [comment]
What @davidyell said. Though I personally think that route is a dead-end for future development.

Good work to @davidyell though!

**Comment by dreamingmind** [comment]
becoming enlightened. thanks

**Comment by davidyell** [comment]
Well we did chat about it in irc @josegonzalez ;)

**Comment by genellern** [comment]
Thank you for replying guys.

**Comment by josegonzalez** [comment]
@davidyell what api changes are there between this plugin and yours? I know you modeled it pretty close and then decided not to push as a new branch, but it might help people upgrade if they have a "stable" upgrade path of some sort.

**Comment by davidyell** [comment]
The behaviour configuration is the same, except on the `thumbnailSizes` as I used Imagine, which I kinda regret as it's so complicated.

As for actual api changes, quite a few, as you'd imagine. I've got a path class which deals with all the file naming, folders, etc, and also I've abstracted the ImageTransform into a class.

Otherwise the way the actual behaviour works internally is very similar. I've also added a few shells for certain tasks which I needed, such as regenerating the thumbnails and cleaning up old images.

I've not hit too many bug reports, but fleshing out the functionality a bit is on my todo list before a 1.0.0 release.

**Comment by josegonzalez** [comment]
On a complete lark, I started [rewriting cakephp-upload for 3.x](https://github.com/josegonzalez/cakephp-upload/tree/3.x). It is missing almost all of the current feature-set. Here's what I'm planning:

- Create a separate, companion plugin that just does file upload validation. Standalone, use it or don't.
- Fix issues where `{primaryKey}` isn't a valid replacement (like on entity creation).
- Potentially re-add `thumbnailSizes`. Honestly, I might just chuck this and show in the docs how to create thumbnails of various sizes.
- Test shells
- Ensure polymorphic behavior works
- Add some goddamn tests and write some docs.

I do plan on dropping a few features, but will document what to do in all cases so that the migration isn't *too* painful.

One positive change! This thing supports uploading files to wherever the hell you want. Want to upload to S3? Easy-peasy. Same for dropbox. Etc.

There aren't any docs, but here is what currently works (tested with uploading to S3):

```
$this->addBehavior('Josegonzalez/Upload.Upload', [
    'photo' => [
        'adapter' => function () {
            $client = \Aws\S3\S3Client::factory([
                'credentials' => [
                    'key'    => getenv('AWS_ACCESS_KEY'),
                    'secret' => getenv('AWS_SECRET_KEY'),
                ],
                'region' => getenv('AWS_REGION'),
                'version' => 'latest',
            ]);

            $adapter = new \League\Flysystem\AwsS3v3\AwsS3Adapter(
                $client, 
                getenv('AWS_BUCKET')
            );
        },
        'rootDir' => WWW_ROOT,
        'path' => 'files{DS}{model}{DS}{field}{DS}{primaryKey}',
        'fields' => [
            'dir' => 'dir',
        ],
    ],
]);
```

yay alcohol and boredom!

**Comment by josegonzalez** [comment]
open pr: https://github.com/josegonzalez/cakephp-upload/pull/314

**Comment by mlumbroso** [comment]
Damn, this is nice :-) Any way to support you, like Flattr or equivalent?

**Comment by genellern** [comment]
Hey Jose, I have some free time, do you want any help?

**Comment by josegonzalez** [comment]
I pushed my latest code. I need to test `initialize` and `beforeMarshal` (the latter fails miserably). If you want to make a pr to fix that test/test initialize, that would be dope. I'm shooting for 100% unit test coverage.

**Comment by josegonzalez** [comment]
All is tested, just needs docs now. To keep the behavior simple, I'm not going to do file validations of any kind for now. That should be a separate plugin.

**Comment by josegonzalez** [comment]
@mlumbroso I have a gratipay! https://gratipay.com/~josegonzalez/

**Comment by vaughany** [comment]
I would dearly like to see the docs updated so I can start using it. (I'm trying, but I'm not that experienced with CakePHP, and certainly not with 2.x to 3.x upgrading, and guesswork isn't getting me very far :/ )

**Comment by josegonzalez** [comment]
@vaughany I haven't had much time to work on the branch (other than get it to more or less where I want it to be). Might have some time this weekend. In the meantime, you may want to ping @ADmad on irc :)

**Comment by josegonzalez** [comment]
Released a 3.x version. 

Given that I don't use CakePHP for my day job, I'm only going to maintain that version, and any pull requests *must* have 100% test coverage *and* documentation, otherwise I won't merge and will probably close them after a set period of time.

Thanks for waiting for a release.

**Comment by nelson6e65** [comment]
Thank you. :smiley:
