### ISSUE TITLE
Update Upload on Edit

### ISSUE THREAD

**Issue by Asyraf-wa** [josegonzalez/cakephp-upload#343]
Hello,

I've already search for solution and found that we need to delete the file first before update with new document but i've no idea on how to do that.

Ok, the situation is, i already upload a file and everything goes very well. All information, filename, dir, size and type has been successfully recorded to the database and i'm able to download the file back. However, when i do update the record, it seem like only filename were updated, but the dir, size and type is not update with the new uploaded record and the uploaded file seem like not uploading to the directory.

How can i solve this issues? how to delete the previous uploaded item? Seriously, this plugin is very good and i'm totally impressed with it. 

btw, i'm using cake 2
Thanks.

**Comment by josegonzalez** [comment]
Do you have a reproduction of this issue?

**Comment by Asyraf1985** [comment]
Model:
public $actsAs = array(\
        'Upload.Upload' => array(
            'picture' => array(
                'fields' => array(
                    'dir' => 'picture_dir',
                    'type' => 'type', 
                    'size' => 'size'
                ),
            'deleteOnUpdate' => true,
            'deleteFolderOnDelete' => true,
            'mode' => 0777,
            'path' => '{ROOT}webroot{DS}files{DS}{field}{DS}',
            )
        )
    );

View:
<?php echo $this->Form->create('User', array('role' => 'file')); ?>

<div class="form-group">
<?php echo $this->Form->input('id', array('class' => 'form-control', 'placeholder' => 'Id'));?>
</div>
				
<div class="form-group">
<?php echo $this->Form->input('User.picture', array(
'class' => 'form-control',
'label' => 'User Profile Picture', 
'type' => 'file'));?>
</div>		
				
<div class="form-group">
<?php echo $this->Form->input('User.picture_dir', array(
'type' => 'hidden'));
?>
</div>

<div class="form-group">
<?php echo $this->Form->input('User.type', array(
'type' => 'hidden'));
?>
</div>

<div class="form-group">
<?php echo $this->Form->input('User.size', array(
'type' => 'hidden'));
?>
</div>	

<div class="form-group">
<?php echo $this->Form->submit(__('Submit'), array('class' => 'btn btn-default')); ?>
</div>

<?php echo $this->Form->end() ?>

Thanks for replying. I don't understand what you mean by reproduction of this issues. Basically i have search and found out that i need to delete the file first before update or do i missed anything? because when i edit, and upload new file, it only capture the file name (picture) but the file is not uploaded.

thanks.
