### ISSUE TITLE
Can upload image without Error { Allowed memory size of 67108864 bytes exhausted } ?

### ISSUE THREAD

**Issue by FauziFerdiansyah** [josegonzalez/cakephp-upload#366]
i have <font style="color:red">Error</font> After Save ... 

`Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 14592 bytes) in /home/content/40/12662440/html/goldsgym/app/Plugin/Upload/Model/Behavior/UploadBehavior.php on line 1511`

Why.. can you help me ? 

In Localhost .. Done but in Server hosting goddady Error ..

Thanks @josegonzalez

**Comment by davidyell** [comment]
This is most likely because the file you are trying to upload is too large, or you are trying to create image thumbnails which are too big.

The only real way to tackle it is to validate the size of the uploaded file, or increase the allowed memory limit which will require editing your `php.ini` file, which you'll most likely not be able to do on your shared hosting.

**Comment by josegonzalez** [comment]
That is correct. You need to give php more memory.
